# Generated by Django 3.2 on 2022-10-25 14:08

from django.db import migrations, models
import django.db.models.deletion
import sensor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pressureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelSensor', models.CharField(max_length=200, validators=[sensor.models.pressureSensor.validation])),
                ('installationDate', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('serial_number', models.CharField(default=uuid.uuid4, editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readingDate', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=10, max_digits=19)),
                ('row_value', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.pressuresensor')),
            ],
        ),
    ]
